# Generated by Django 5.0.6 on 2024-06-01 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_label_name_alter_label_owner_alter_task_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_label_per_owner',
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='owner_name'),
        ),
    ]
